### ISSUE TITLE
analysis links.json has duplicated process entries

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/metadata-schema#1065]
in bundlke 575a1f21-d648-488f-9c41-51a2ad5f11d2

links.json has process entries that are duplicated
[links.json.gz](https://github.com/HumanCellAtlas/metadata-schema/files/3379697/links.json.gz)

**Comment by malloryfreeberg** [comment]
@diekhans I don't think this is a bug in the metadata schema. The duplicated processes likely comes from the ingest exporter which builds the links.json as part of the submission of processing results for a secondary (analysis) bundle. This ticket is probably better suited in the ingest-central repo. 

There's also a possibility that the duplicated processes is coming from the data processing pipelines themselves. As I understand it, the links in `links.json` for secondary bundles are made by the data processing pipelines using an ingest-api endpoint to create entities/links. Perhaps they are pinging the endpoint multiple times? I'm not clear if they are only creating the new analysis processes or also reconstructing the whole `links.json` including links from the primary bundle. So, this ticket might possibly belong in the pipelines repo, too.

@rolando-ebi @rexwangcc any insight here?

**Comment by rolando-ebi** [comment]
@diekhans @malloryfreeberg there is a legitimate bug in the ingest export process here. When crawling the experiment graph, links are stored in a list rather than a set so it's possible for a link to be added twice. Could also be solved by keeping track of visited/unvisited nodes. I'm tracking this in a new issue here: https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/459

**Comment by malloryfreeberg** [comment]
Thanks @rolando-ebi ! Closing this issue here.
