### ISSUE TITLE
Update the schema description for `analysis_process`

### ISSUE THREAD

**Issue by rexwangcc** [HumanCellAtlas/metadata-schema#1106]
**For which schema is a change/update being suggested?**

*e.g.*: I would like to request an update to the `analysis_process.json` schema.

**What should the change/update be?**

* Field description: FQID(s) of the input bundle(s) used in running the pipeline.
* Field example: "b816d2d6-5f10-4447-4194-3d0a804454d6.2019-08-26T200249.968117Z"

**Why is the change requested?**

The current field only requires the analysis include UUIDs as the `input_bundles`, which will not be sufficient anymore for the bundle versioning feature (AUDR). We need both the UUID and the version of the bundles to better track the bundles through the whole system. A more detailed discussion can be found on Slack: https://humancellatlas.slack.com/archives/C6C5S6B5W/p1566849676197100

**Comment by justincc** [comment]
In itself this should have no ingest impact since ingest doesn't use this field. However, to actually specify input files to an analysis older than the latest, ingest needs to be able to accept FQIDs when the analysis process is specified (I don't know the exact mechanism here, perhaps you could help @rolando-ebi @alegria?). Then without going and putting the FQIDs in `links.json` the user won't be able to see these relationships unless they download the DSS bundle manifest. If we edit `links.json` then we need to carefully consider the implications for AUDR since `links.json` will then need an update whenever any file in a bundle is updated.

**Comment by justincc** [comment]
This can't be done in isolation since ingest soon won't be using this field to determine what to copy forward. Instead we will be looking at the input files to the analysis process. So this needs to be a solution inconjunction with whatever work we discover is needed in https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/528

**Comment by justincc** [comment]
@parthshahva
