### ISSUE TITLE
10x sequencing names inconsistently mention the end bias

### ISSUE THREAD

**Issue by ambrosejcarr** [HumanCellAtlas/metadata-schema#1122]
Metadata "Library Construction Method" appears inconsistent to me: for "10X 3' v1" and "10X v2" why mention 3' in only one? 

Observed via the Data Portal.

**Comment by claymfischer** [comment]
This is an inconsistency we would like to update post-Barelona. This is being discussed in slack (#data-pipelines-team) by @mshadbolt to ensure this update are not disruptive.

**Comment by ambrosejcarr** [comment]
Agree, non-urgent.

**Comment by mshadbolt** [comment]
We are staying with using the generic "10X v2 sequencing" until after Barcelona, then once given the all clear that AUDR is working wranglers will work on ensuring all projects consistently use the more specific term. We have also flagged this with pipelines so that they update their queries to the more specific terms.

**Comment by ESapenaVentura** [comment]
There are ongoing efforts to harmonise the library preparation protocol methods with the most specific technology.

Closing the ticket.
