### ISSUE TITLE
Add harmonized cell type annotations to output files for the March release

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1224]
**Description**

As a HCA wrangler who is responsible for providing accurate data and metadata to the Portal users, I would like to harmonize and add cell type annotations in the output files that will be used in the Data Portal release page.

This builds on results of https://github.com/HumanCellAtlas/metadata-schema/issues/1221

**Acceptance Criteria**

- [x] Clusters in all the loom files are annotated with the harmonized list
- [x] Clusters in all the h5ad files are annotated with the harmonized list
- [x] Clusters in all the SCP metadata files are annotated with the harmonized list

**Comment by lauraclarke** [comment]
We need to write up a plan for this process and then I expect there might be a bunch of steps which either get recorded in this ticket or with a spreadsheet maybe Kylee's to track the process.

**Comment by mshadbolt** [comment]
As a proof of concept I have figured out the process for adding a cell_type column attribute to an existing loom file, using the Gary Bader Liver Landscape loom as an example, the step by step process is here: https://github.com/ebi-ait/hca-documentation/blob/master/walkthroughs/Add%20cell%20type%20to%20loom.ipynb

My thoughts are that we should come up with a standard way of representing the cell types, probably something like:
`cell_type.text` - the text field from the contributor's paper
`cell_type.ontology` - the curated ontology curie i.e `CL:00000#`
`cell_type.ontology_label` - the curated ontology label
But happy to hear other suggestions for the field names here.

One thing worth noting perhaps is that not all cells in the matrix get annotated as it depends on how the cells were filtered before they were clustered.

This was a nice straight forward id matching process where it was easy to match the cells by the barcode and we had the same identifiers in our system. It might be hard to write a fully automated script as there will always be a bit of manual work in figuring out how the id matching will work.

**Comment by dosumis** [comment]
Looks good.

_Suggestion_: It might be useful  to add a pub field to record the preprint or full pub that supports this cell-type annotation.  If this gets re-annnotated later, it will be useful to have a record where the original annotations came from.

_One question_: Do  you need to support multiple ontology term associations?  Here's an example of cell type  annotation in a Loom file from http://loom.linnarssonlab.org/:

![image](https://user-images.githubusercontent.com/112839/73918761-216b0480-48ba-11ea-8a0c-3f0a8d89fe5d.png)

Some free text annotations map to multiple CL terms - presumably reflecting ambiguity in assignment.  Here's how I mapped:

![image](https://user-images.githubusercontent.com/112839/73918833-4b242b80-48ba-11ea-8967-b69adfb36a05.png) 

I've come across this quite often in FlyCellAtlas mappings

(https://github.com/HumanCellAtlas/matrix_semantic_map)

**Comment by mshadbolt** [comment]
thanks @dosumis that is useful feedback

We haven't started trying to ontologise all the cell types yes but you are probably right that we might need chaining in order to get the specificity that we are after. It is great to have an example of how we might do that so thank you for that. If we are having trouble when we start doing the mappings we might come ask for more help.

**Comment by mshadbolt** [comment]
Zina gave the following spreadsheet as the ontologised cell types for the Bader dataset

https://docs.google.com/spreadsheets/d/15jfRa-qLC38i7nlvHhOdsrvPWWTYaXhdP_WtsE_z1xg/edit?nativeconvert=1#gid=1322894501

**Comment by mshadbolt** [comment]
I have a python script that works to update loom, h5ad and metadata.txt files.

As input it needs the loom, h5ad and metadata files from the SCP, along with a csv file that contains the cell annotations. This needs to be of a particular format which I created manually but will look at creating in a more automated way now that the format is defined and when all cell types are ready.

I will put the updated files into the shared s3 space and let the broad know so that they can check to see that they are the format they were expecting.

Currently I think it will only work for 10x data but I will need to make updates to allow it to work for SS2 once I have some example files.

I have put the 3 updated files into the folder `CumulusHCADemo_annotated` in the shared s3 bucket for the release.

**Comment by mshadbolt** [comment]
@zperova finished the cell type annotation which is in this google sheet: https://docs.google.com/spreadsheets/d/1WikuK2mlFhAqCfWuPJIwBAGsevTO156cRkFXur6LkCs/edit#gid=231487397
Column A - is the contributor’s term
Column B is harmonised term
Column C - ontology label
Column E - ontology id

So based on your email zina you want the column titles in the loom, h5ad and metadata files to be:
`annotated_cell_identity.text`
`annotated_cell_identity.ontology`
`annotated_cell_identity.ontology_label`

In the spreadsheet an '_' is used in the ontology curies, is this preferred instead of a ':'?

Are the spaces when there is more than one curie desired/necessary? e.g. `CL_0000990 || CL_0000451`

**Comment by mshadbolt** [comment]
also @zperova are we putting both the contributor's term and the 'harmonised' term into the outputs?

**Comment by mshadbolt** [comment]
also how come for some projects you chose to identify the cell type, then the organ location whereas others just have an organ? one example is for the tissue sensitivity oesophagus epithelial cells. 
e.g.

Epi dividing | dividing epithelial cell | epithelium of esophagus | Medium | UBERON_0001976
-- | -- | -- | -- | --

whereas:

Pelvic epithelium - distal UB | pelvic epithelium cell - distal ureteric bud | ephithelial cell \|\| ureteric bud | Medium | CL_0000066 \|\| UBERON_0000084
-- | -- | -- | -- | --

**Comment by dosumis** [comment]
> also how come for some projects you chose to identify the cell type, then the organ location whereas others just have an organ? one example is for the tissue sensitivity oesophagus epithelial cells.

Better to have an actual cell type term as one of the annotations.  Uberon alone will often be ambiguous - as could be the location of multiple cell types.

**Comment by zperova** [comment]
@dosumis I would be keen to hear your view point on the following:

while there is a term for the activated state of T cell: https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001049
there does not seem to be a term for resting T cell

What is the reasoning behind adding a term for activated state but not resting state?

**Comment by dosumis** [comment]
> @dosumis I would be keen to hear your view point on the following:

> while there is a term for the activated state of T cell: https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0001049 there does not seem to be a term for resting T cell

> What is the reasoning behind adding a term for activated state but not resting state?

I've asked our immune cell expert on the CL tracker:

https://github.com/obophenotype/cell-ontology/issues/640

**Comment by mshadbolt** [comment]
Summarising some outcomes from the meeting I had with @zperova today

The current list of harmonized cell types is here: https://drive.google.com/open?id=1gF3JBZwD4JIQQ8DlNNDsK9-ws1XQJldX

The mapping of fields I will add to outputs and fields in this spreadsheet are:
`annotated_cell_identity.text` = `HARMONIZED CELL IDENTITY`
`annotated_cell_identity.ontology` = `ONTOLOGY TERM(S)`
`annotated_cell_identity.ontology_label` = `ONTOLOGY TERM LABEL(S)`

I will remove the white space that exists between the terms and the pipes 
I will replace underscores with `:` in the `ONTOLOGY TERM(S)`

I will start working on the datasets that have "confirmed annotations" as noted in the release tracker spreadsheet.

When I have updated the loom file, h5ad file and metadata txt file I will add these files on the SCP instance. It is still to be confirmed whether I will need to delete the existing unannotated loom and h5ad files as there was talk of backing these up somewhere but I don't believe that we have the resource or capability to do this.

**Comment by zperova** [comment]
thanks @dosumis I have followed up on this in the CL ticket.
