### ISSUE TITLE
Provide feedback on the UCSC initial Terra Data Repository HCA data model [KR2]

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#1268]
# Feedback on the UCSC initial Terra Data Repository HCA data model

@hannes-ucsc and @theathorn have written a proposal for how the HCA metadata schema will be represented in the Terra Data repository

https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit#heading=h.aee8p3q0sp0m

The goal of this ticket is to engage in the discussion about this proposal and influence the outcome of the decisions being made around how links between entities are stored in the TDR BigQuery schema 

- We need to ensure the proposed model can represent the metadata captured from curators
- We should understand the trade-offs in a mapping which is very close to the HCA metadata entities and schema compared to something which is more closely aligned with the Terra Data repository

### Acceptance criteria
- [ ] Feedback provided on the data model proposal to influence the outcome

**Comment by mshadbolt** [comment]
Questions for @lauraclarke :
1. What would be the best format to provide feedback? Should I provide feedback as comments in the original document?

Proposed plan forward:
* All wranglers to read through the document
* Wranglers to provide any comments or questions here on the ticket
* Marion to lead providing consolidated feedback to the data portal

**Comment by lauraclarke** [comment]
I like the proposed plan, create consolidated feedback and add it to the document.

Whoever is lead on this should be included with me (and whoever is responsible on @justincc's side) in any meetings that are scheduled about this by @hannes-ucsc and @theathorn or others

**Comment by hannes-ucsc** [comment]
I'd recommend that questions about specific sections be made as comments, or inline in the "Open questions"  section. Typos and grammatical errors can be fixed with direct edits. More substantial wording changes should be made using the suggest changes feature.

General feedback or potentially contentious points (as "I disagree with assumptions this document makes") should not be made as a comment since those typically end up becoming long threads that crowd the document. Instead, I'd prefer a subsection to be added to the discussion section. When adding such subsections it would be helpful to tag them with the author's name or email.

**Comment by mshadbolt** [comment]
I read through the document but I don't think I can provide any useful feedback. 

It tries to describe a lot of technical detail about concepts I don't really understand to do with TDR, BQ tables and don't have the knowledge or experience to know whether what is being proposed is sensible or not.

I don't have a concept of what the TDR database schemas or TDR tables might be or look like.

As a more visual person I would personally appreciate some kind of diagram or example to help understand, but again maybe I just don't understand because I don't understand the background.

As a data wrangler and part of the metadata team all I really care about is that all the metadata that we put into the system is able to be retrieved at the other end by a user in a similar or at least usable structure, and nothing is lost along the way.

**Comment by ESapenaVentura** [comment]
I have gone through it, and here are my thoughts:

First paragraph:

- Are we going to use the same metric as before to define minor, major and patch updates to the schema?
   - (Also does that mean we can push minor changes before the MVP is ready?)

SPECIFICATION
- How useful it is to have the UUID duplicated in the content? in an SQL-like database, isn't it worth to not have the Primary Key repeated?
- Is the idea to never update a row in a table? Having a column in the table that would be `latest_version` and a boolean would make it very easy to query for the latest versions of datasets and to create snapshots with the latest data. This would get updated only once, when a dataset with the same PK is introduced.

OPTION A :
- How are the rows for `links.json` going to get big? They don't display (At least for what I've understood reading the document) the content of the file, they just store it verbatim.

CONCLUSSIONS:
- DCP v1 is going to be retired? what does this mean exactly? There are still papers out there with DCP1 "accessions", even if it's not updated anymore will it be maintained?

Overall looks good, my understanding of relational databases is pretty limited but I like the ideas exposed there. The data file path is not too clear (What is this path going to be? buckets?) but I guess that would be better defined later.

**Comment by theathorn** [comment]
@ESapenaVentura It would be best if comments could be made directly in the document.

>> DCP v1 is going to be retired?
Yes, that is the plan. When DCP/2 is online CZI will tear down the DCP/1 infrastructure. data.humancellatlas.org will be redirected to the portal in DCP/2. Project citation URLs (e.g. https://data.humancellatlas.org/explore/projects/f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc) will be preserved. I'm not aware of any other type of "accessions".

**Comment by ESapenaVentura** [comment]
Hi @theathorn , we initially planned on giving feedback through here and then a wrangler would consolidate it and put it in the document, but this plan has changed and I didn't catch it so that's why I put it here.

I will proceed to comment in the document! Sorry for the misunderstanding
