### ISSUE TITLE
Update pullapprove.yaml config file to not notify about major schema changes

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#1280]
**Description**

As a DCP wrangler from the metadata team, I would like to update pullapprove's yaml config file to not notify a list of users from other components when a major schema change is being made. This is not needed moving towards DCP2

 

**Acceptance Criteria**

- [ ] https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml#L30-L36 has been deleted from the config file.

**Comment by mshadbolt** [comment]
I think that perhaps we should revise the list rather than deleting, I imagine downstream components will still want to know about the changes we make to metadata schemas

**Comment by ESapenaVentura** [comment]
This stems from a conversation with @lauraclarke 

Maybe updating the list is a better idea rather than deleting it, but I thought we would be more independent when making changes?

**Comment by mshadbolt** [comment]
Yes I don't think that other components will be blocking us but they do need to know when metadata is updated so that they can work toward supporting the change. Unless there is another plan to communicate this I don't see why we would stop informing the DCP when we make changes.

**Comment by lauraclarke** [comment]
This sound like a proposal we should make to the other members of the DCP

What was the goal of this list previously?
Do you feel this is still a useful goal?

If we want some sort of list, who should I ask about membership
I can think of  
- TDR ingest
- TDR storage, 
- Broad Pipelines 
- UCSC Browser/Portal 

Anyone else?

**Comment by ESapenaVentura** [comment]
The goal of this list was for all the components to be aligned with our metadata changes and ensure no component was broken due to unexpected metadata updates.

In reality we never got to test it as we didn't make any major metadata change.

Moving forward I think it's useful, and to add to the list, maybe we should also include `EBI ingest`, as even if we work in the same team the devs do not check this repo regularly

**Comment by mshadbolt** [comment]
The goal of this list was so that when the schemas changed the components that rely on the schema would be informed.

Yes I still feel this is a useful goal unless you have a better idea for informing other components about this.

I don't know anymore who is directly affected by schema changes. Pipelines, browser and portal were already in the list. The question is about TDR ingest and storage, in the current plan they are somewhat agnostic to schema changes due to the way we are putting json content in a blob so not sure whether changes we make at the moment would affect them until we get to the point of properly modelling our metadata within TDR.

**Comment by lauraclarke** [comment]
Great, so keeping the list is a good idea

Is it reasonable to say we need to know who from pipelines and browser/portal should be on the list

and we should ask if anyone from TDR or ingest wants to be on the list in the short term and make them aware they can always ask to be added later if they don't want 

Are there any other DCP components/interested parties that you think we should ask?

As an aside, I think we need to review the other lists covered by this file but not the problem to solve here

**Comment by mshadbolt** [comment]
I believe we had checked with browser/portal and pipelines who would be best to add to the list when we created it but it would be worth re-checking as I'm not sure if the teams have changed.

Yes I think it would be good to as whether the TDR teams would want to be added.

I dont think I have a good understanding of the current DCP components since the change so not sure who else would be good to ask. 

@ESapenaVentura could perhaps create a new ticket to address the reviewer lists to remove zperova and cjvillar. not sure if UCSC wranglers will continue to be involved either.

**Comment by lauraclarke** [comment]
I might wait till we have resolution on the links.json schema change as I don't want to distract from that but once that is over I am happy to email a similar list of people to ask who the membership of the pullapprove list should be

I agree @ESapenaVentura creating a ticket for reviewing the other membership lists would be a good plan

**Comment by ESapenaVentura** [comment]
Sounds good, I can create the ticket before the end of today.

**Comment by lauraclarke** [comment]
@ESapenaVentura I want to flag this to the other parts of DCP2. Did you create a new ticket?

**Comment by ESapenaVentura** [comment]
Sorry, I hadn't created it yet.

Done it now, https://github.com/HumanCellAtlas/metadata-schema/issues/1287
