### ISSUE TITLE
Enable capture of portal links and SCEA, EGA & dbGap accessions

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1336]
**For which schema is a change/update being suggested?**

project.json

**What should the change/update be?**

I would like to add at least two optional fields to the project_core.json schema

#### ega accession
* Field name: ega_accessions
* Field description: European Genome Phenome Archive (EGA) dataset or study accession. Study accession preferred.
* Field type: list of strings
* Required: No
* Examples: EGAS00000000001; EGAD00000000002
* pattern: `EGA[DS][0-9]{11}`

#### dbgap accession
* Field name: dbgap_accessions
* Field description: database of Genotypes and Phenotypes (dbGaP) study accession.
* Field type: list of strings
* Required: No
* Examples: phs001997.v1.p1; phs001836
* pattern: `phs[0-9]{6}(\.v[0-9]{1})?(\.p[0-9])?` (this regex should be double checked)

#### scea accession
* Field name: scea_accessions
* Field description: Single cell expression atlas accession.
* Field type: list of strings
* Required: No
* Examples: E-MTAB-6678;E-GEOD-150728
* pattern: `E-[A-Z]{4}-[0-9]+` (this regex should be double checked)

#### contributor portal links
* Field name: portal_links
* Field description: Links to a contributor created web-based portal with visualisations for this project.
* Field type: list of strings
* type: string
* format: uri
* Required: No
* Examples: https://www.heartcellatlas.org/
* pattern: `^https?://.+` (this regex should be double checked)

This update constitutes a minor change to the schema(s) it affects.

**Why is the change requested?**

To support additional links to managed access archives when that is where the data is available and contributor portal links.

**Comment by mshadbolt** [comment]
I expanded this to also include adding extra fields such as scea and analysis portal links

**Comment by mshadbolt** [comment]
I have started working on a branch for this ticket. `ms-add-accessions` will wait for other pending issues/PRs before attempting to PR and merge

**Comment by lauraclarke** [comment]
I am wondering if this is a scalable solution for accessions, every time we have a new accession we add a new attribute

Is there a better way to capture some sort of hash/list that then contains the string and a label to where the accession is for rather than always having an ever-expanding list of X_accession attributes

**Comment by mshadbolt** [comment]
I totally agree, and don't really like adding all these fields, but I don't really see an alternative right now that we could implement on a short time scale. I think we are trying to target the March release for some managed access projects, and feels wrong to not be able to capture accessions for them...

We went down this road a long time ago when it was decided to have individual accession fields for the various archives, so now to pivot to another strategy will mean having to try and migrate all previous projects, or ask browser to support both methods, which is possible, but the consultation and implementation of that will most likely take more time than we have. 

This was too much for my brain to be able to think about, so I went with the dumb simple solution, but if you think it is worth delaying this until we can implement a better solution then that is also fine.

**Comment by mshadbolt** [comment]
Alternative proposal could be to create an 'accession' module and a 'external_link' module where you could have two fields, the field that contains the accession or link, and a field that categorises that accession or link. 

Pros: 
- Doesn't add lots of extra fields  
- adding new archives/link types as simple as adding to the enums rather than creating a new field in the schema

Cons:
- harder to implement in a spreadsheet, would probably have to be new tabs
- how do we validate each accession
- creates work for browser to adapt to this different form
- creates confusion if some of our metadata follows this format and some doesn't OR
- creates migration burden if we want to make all metadata consistent
- adds modules, which I thought we were trying to not do

### Create an accessions module

accession.json as a project module

fieldname: accession
type: list of strings
required: no

fieldname: accession_type
type: enum
- geo
- ega
- insdc
- arrayexpress
- scp
- dbGaP
- scea
- biostudies
- other?
required:no

### Create a links module

fieldname: link
type: list of URI strings

fieldname: link_type
type: enum
- analysis portal
- code
- other?

**Comment by lauraclarke** [comment]
We could stage it, not remove the old fields but start the new better way for these types of accessions and then we could plan the migration of all the old fields to the new system with more time an consideration

The proposed timeline for the first release of EGA data is April so we have bit of time for consultation on the solution

**Comment by ESapenaVentura** [comment]
I like the idea of an accessions module, I just don't understand why the links module

I do agree that the timeline is limited here and if we want to make it, we might want to add the accession fields "the old way" then have a "re-work" of the schemas later on and add these modules

I think this will come in handy:

https://json-schema.org/understanding-json-schema/reference/conditionals.html

We could have an accessions module, with an enum (accession_type) then check for each "accession_type" a specific regex pattern. A problem I see in here is contributors/wranglers filling out the wrong accessions in the wrong places (e.g. nothing stops you from adding a bioSamples accession to the project accession field). We would probably need tests with the graph-validator to check for that.

**Comment by mshadbolt** [comment]
@ESapenaVentura the links module was because recently a contributor said they wanted to see their own 'analysis portal' link displayed in the 'analysis portal' links in the browser. But currently we just have 'supplementary links' with no way for the browser to tell which link could be a link that they should display in that category.

**Comment by lauraclarke** [comment]
I agree that a links module, like an accessions module, allows us to capture more info about supplementary links than we could with a flat list

I agree that the accessions module needs work around validation but that is definitely a solvable problem

**Comment by ESapenaVentura** [comment]
Oh right, sorry, didn't realise the portals linking

I guess thinking about that, do we need a module? or maybe we can re-purpose the supplementary links field?

**Comment by hannes-ucsc** [comment]
I would consider not overloading the term *link* since its already taken (system/links.json) and people might get confused. I think the choice of the term "links" for the current system use was unfortunate and "links" fits this use new use better but I think being unambiguous trumps being descriptive/accurate. Maybe "url" and "urls"?

If there is a straight-forward migration path from documents that comply with the old schema to documents that match the new one, my team can code that into the metadata-api and it would help us adopt the schema change. For schema changes that enrich the data model such a migration path usually exists and it looks like this change is of that category.

**Comment by tburdett** [comment]
Hi @mshadbolt, this is a good proposal. I have a few minor suggestions that may help us implement this cleanly...

1. Implement the chosen accessioning mechanism as a keyword extension (similar to [`graph_restriction`](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema_extensions/ontology_meta.json)) so that we can plug in extensions to the schema validator
1. Exploit [identifiers.org](https://identifiers.org/) as the mechanism for dereferencing accessions. This would avoid the need for the `links` section altogether, as all links would become https://identifiers.org/<accession_type>:<accession> (e.g. https://identifiers.org/geo:GSE113196), **and** we would avoid reinventing [this registry](https://registry.identifiers.org/registry) within our schema in the `accession_type` enum
1. You may want to consider something other than `accession` for the keyword. There are other scenarios too (e.g. contributor ORCiDs) that aren't commonly called accessions. Maybe `external_reference` or something? So, just as we have `diseases.ontology` field that is mapped to the `graph_restriction` keyword, you might expect a `accession` field or an `orcid` field mapped to an `external_reference` keyword

Also tagging @mcourtot and @theisuru for information (and possible support on the JSON Schema Validator)

**Comment by tburdett** [comment]
In a followup conversation, @mshadbolt pointed out that exploiting identifiers.org doesn't actually remove the need for links altogether: this works for accessions, but not for the portal links https://www.heartcellatlas.org/ scenario.

**Comment by mshadbolt** [comment]
Okay it seems there is general agreement on creating modules for these rather than making embedded fields in the `project.json`. 

I will create a new branch for this scenario and seek further feedback on naming and descriptions to ensure we all agree on this and it doesn't cause unnecessary confusion.

I think we would all want to migrate all the existing metadata to this new structure some time after the change is implemented, though we (ingest) have not ever undertaken any kind of migration to date. Agree it should be possible via fairly simple logic. 

There is also some work in ingest ui for us to be able to allow this information to be entered by a user in this different format.

**Comment by mshadbolt** [comment]
Oh I just thought of another question, would this accession module replace only the project level accessions, or would it replace accessions in biomaterials as well?

**Comment by hannes-ucsc** [comment]
If I may, the "managed access" at the beginning of the title is a little misleading. It confused me for a second.

**Comment by mshadbolt** [comment]
We are going to revert to the original, simplified plan of adding optional accessions of each type to the project as these will be simpler support and won't require migration of existing projects.
