### ISSUE TITLE
add hca_publication flag to publications module

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1345]
**For which schema is a change/update being suggested?**

publications.json

**What should the change/update be?**

Add an optional field to indicate when a publication has been through official process to be classified as an HCA publication (https://www.humancellatlas.org/publications/)

This update constitutes a minor change to the schema(s) it affects.

**What new field(s) need to be changed/added?**

* Field name: hca_publication_status
* Field description: Has the publication been accepted as an official HCA publication according to the process at https://www.humancellatlas.org/publications/
* Field type: boolean
* Required: no

**Why is the change requested?**

We don't currently have a way of identifying which of the projects in the browser are official HCA publications.

**Comment by lauraclarke** [comment]
I would advocate for sticking with hca accepted or unknown because I think the overhead of being able to tell when something changes from pre-print to publication is quite high, especially as the HCA publication list on the website rarely gets changes so I am not sure the value we get for having the differentiation is worth the effort involved in keeping it up to date

**Comment by mshadbolt** [comment]
ok that is more simple, we can make this a boolean true/false yes/no field then

**Comment by ESapenaVentura** [comment]
https://github.com/HumanCellAtlas/metadata-schema/pull/1388
