### ISSUE TITLE
Schema update: update library preparation protocol barcode fields

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/metadata-schema#1407]
**For which schema is a change/update being suggested?**

I would like to request an update to the `library_preparation_protocol.json` schema.

**What should the change/update be?**

Adding new fields.

Add new fields for 10X visium spatial library construction method spatial barcodes. Spatial barcode read, spatial barcode length, spatial barcode offset.

This update constitutes a minor change to the schema(s) it affects.

**What new field(s) need to be changed/added?**

library_preparation_protocol.spatial_barcode.barcode_read
library_preparation_protocol.spatial_barcode.barcode_offset
library_preparation_protocol.spatial_barcode.barcode_length

**Field name**
spatial_barcode.barcode_read
spatial_barcode.barcode_offset
spatial_barcode.barcode_length

**Field description**
The read in which the barcode is found.
The 0-based offset of start of barcode in read.
Length of barcode in nucleotides.

**Field type**
str
integer or list of integers
integer or list of integers

**Required**
yes, if library construction method ontology label is visium spatial gene expression data (new ontology term for this technology has been requested)
yes, if library construction method ontology label is visium spatial gene expression data (new ontology term for this technology has been requested)
yes, if library construction method ontology label is visium spatial gene expression data (new ontology term for this technology has been requested)

**Examples**
Read 1
0
16

**CV or enum**
yes: Read 1, Read 2, i7 Index, or i5 Index
no
no

**Why is the change requested?**

So that 10X visium spatial gene expression data can be interpreted and processed by both the pipelines team (if/when they implemented a visium spatial data workflow and by a contributor/user of the data.

**Comment by Wkt8** [comment]
Needs a bit of editing as it involves editing the barcode_module.

**Comment by Wkt8** [comment]
This is effectively loading the [barcode_module](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/module/process/sequencing/barcode.json) with spatial_barcode in the library_preparation_protocol schema (https://github.com/HumanCellAtlas/metadata-schema/blob/ff27788edc635f6e631a64b3fcda63f54fc6fe7b/json_schema/type/protocol/sequencing/library_preparation_protocol.json). 

For which schema is a change/update being suggested?

I would like to request an update to the library_preparation_protocol.json schema.

What should the change/update be?

Load the 'barcode' module found [here](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/module/process/sequencing/barcode.json) with spatial_barcode. This will add new fields for 10X visium spatial library construction method spatial barcodes. 

This update constitutes a minor change to the schema(s) it affects.

What new field(s) need to be changed/added?
library_preparation_protocol.spatial_barcode

Field name
spatial_barcode

Field description
Information about spatial barcodes

Field type
object with $ref": "module/process/sequencing/barcode.json

Required
Optional - only required if library construction method ontology label is visium spatial gene expression data (new ontology term for this technology has been requested)

Why is the change requested?

So that 10X visium spatial gene expression data can be interpreted and processed by both the pipelines team (if/when they implemented a visium spatial data workflow and by a contributor/user of the data.
