### ISSUE TITLE
F2F Meeting: Resource Bundle Metadata Schema

### ISSUE THREAD

**Issue by kbergin** [HumanCellAtlas/metadata-schema#208]
Aims: Working session to choose metadata for a reference bundle and check any needs by the blue box for indexing.

Outcomes: a PR for resource metadata schema

We will need representation from green on engineering and pipeline side, and from blue box, someone familiar with indexing and the communication between green and blue.

**Comment by malloryfreeberg** [comment]
Since this will be a working session to produce a PR for adding a new schema, I suggest the following roles for this session:

**Co-leads - lead discussion, present requirements for reference bundle, :**
Dani @daniwelter (ingest)
Jishu @jishuxu (pipelines)
Trent @Bento007 (indexing)

**Hacking - make reference bundle JSON schema that meets the needs of all teams, open a PR:**
Mallory (ingest)

At the end of the session, I will make a PR and the metadata team will follow the update process for incorporating new metadata schema.

**Comment by malloryfreeberg** [comment]
Closing this issue as it was addressed by commit 95fea68.
