### ISSUE TITLE
Add two fields to project core for funder and grant title.

### ISSUE THREAD

**Issue by cjvillar** [HumanCellAtlas/metadata-schema#225]
Adding request information:

"Hello!
I'd like to request an update to the metadata schema. The changes I'd suggest are as follows:

1 - this would be a change to the core "project" schema
2- Don't think there is a field that currently exists. 
3 - It would be a new field that is free text and something along the lines of "Funder and specific grant number" could be broken up into two fields (e.g. 1) Funder 2) grant title). 

4 - This change is being requested to help HCA funders, track and understand specifically what data they have supported. Ideally, a funder would be able to browse or identify exactly which data they have supported and also the specific grant/program that the data came out of. It will be critical to rationalizing funding and also a metric that funders can track to evaluate impact/effectiveness of specific programs. 

All the best,

Jonah"

**Comment by malloryfreeberg** [comment]
Thanks for the suggestion! Please confirm that the new field address your need:

Field name: Grant name
Description: The name of the grant funding the project.
Example: NSF Grant 0903629
Required: No

**Comment by cjvillar** [comment]
Should we create two separate fields one for the name and the other for the grant ID?

**Comment by lauraclarke** [comment]
@cjvillar is correct, we should collect grant title, grant id and funder name

At somepoint, we will then want to review funder names and maybe make it a controlled vocabulary

I also expect that some people will be running these projects using multiple funding streams so we might need these things to be an array rather than just one of each

As I said, there is a plan to give funders their own ids that work like ORCID ids but I think if we have three fields, adding a funder id wouldn't be that much additional work

**Comment by jonahcool** [comment]
@lauraclarke @cjvillar agree that the 3 fields is probably best. May even be able to introduce some CV for certain funder fields to help each funder quickly identify work that they are supporting.

**Comment by freeman-lab** [comment]
congrats on your first github comment @jonahcool 👍

**Comment by malloryfreeberg** [comment]
@lauraclarke @jonahcool I'm on board with adding grant ID and funder name fields. My concern with adding a grant title field is that the value for this field might be the same as the project title. In fact, the example we have give for the project title field is "A title of a grant proposal or publication." While I'm aware that a project title and grant title might not always be the same, I wonder whether we are better served asking submitters to spend their time/energy filling in fields more useful for describing their data rather than how they were funded.

@jonahcool Regarding having a CV for funder fields, if we can define these vocabularies now, that would be ideal. Adding a CV to a field after it's already been released is a major breaking change. What were you envisioning the CV for something like "funder name" to contain? e.g. "NIH" versus "National Institutes of Health"? Adding to an already existing CV is not a breaking change, meaning it's easier to add funders to an existing CV.

**Comment by jonahcool** [comment]
@malloryfreeberg agree that the title of the grant is likely to be close to the project title. Your intuition about restraining the fields to funders and grant ID is perfect.

for the CV - you've got it. Just trying to avoid confusion on NIH v National Institute of Health or CZI v Chan Zuckerberg etc. I feel confident that we could develop this easily by asking the funders to define what they want their CV term to be. Then they can add it into grant agreements or make it known to the community. We can add over time but that would allow a good baseline.

**Comment by lauraclarke** [comment]
@jonahcool @malloryfreeberg 

On the project title/grant title thing, it might be the same but say if the WT awards a large collaborative award to several data generations centres, their individual studies will likely have different titles to the whole award so having the grant title might help to make this distinction. This is the same reason that I might be tempted to allow this to be an array of funders rather than a singular funder as some projects may be drawing on funds from a collection of grants rather than a single one

Jonah, if you can coordinate a set of funder names through the funders group that would be great.

**Comment by lauraclarke** [comment]
@malloryfreeberg @jonahcool One reason to have a distinct grant name to project title is for some grants will end up running in distinct studies, e.g if NIH, WT or EU fund a large award where multiple organ systems or assay modalities are all run through the same funding stream, the data generators might want to have the projects divided at a higher level of granularity than the funding award.

The converse might also be true. Some data generators might pull together funding for multiple streams and want to run a single project using all of them, this is why we should allow multiple funder declarations if possible.

@jonahcool if you could speak to the other funders and propose an initial list of funder names, that would be great

**Comment by malloryfreeberg** [comment]
@lauraclarke I'm fine with having these fields be an array. In the future there must be a way that a submitter can input a grant ID and automatically the funder name and grant title could be populated. 

I am inclined to make funder information optional (but strongly recommended) at this point. Thoughts?

**Comment by gabsie** [comment]
Hi, 

Stepping into users’ shoes, I would be inclined to also have this information optional, and being entered at the level of the project.

However, we need to look into example grants, funders and projects, to understand what is the optimal way to arrange them and avoid duplication of entries.

We have already introduced datasets as parts of Projects. And Projects so far I have almost considered something you get funding for, thus overlapping with the idea of a grant.

In that case, isn’t it a matter of only adding an extra field for Funder name or some form of number, to add further information on a project?

We should also consider (as with any field) Why we need this information — in terms of stories. 
As somebody browsing the data, I want to look up who has funded this project, in order to ……. ?

and whether the person entering the dataset will have this information.

Gabs

**Comment by lauraclarke** [comment]
I am happy for this to be optional. I think @gabsie is correct that in the first place, the person entering this information won't necessarily know but if we can end up in the position where the project manager is the one to register the project (This is where this should be tracked) then hopefully it is much more likely

That being said @gabsie these fields have a significant political win in helping the funders track who has deposited what data

@malloryfreeberg  long term, we will want interfaces which work to recruit the data from things like the name of the funder and the name of the project, that will be a future feature when services like https://www.crossref.org/services/funder-registry/ are much more fully formed

**Comment by jonahcool** [comment]
@lauraclarke @malloryfreeberg @gabsie agree that optional is fine. Funders can mandate for reporting, if need be. Also agree that this is very important for politics but also potentially for program-specific portal construction (e.g. portal for all of the BRAINI BICCN data).

**Comment by malloryfreeberg** [comment]
Release with commit 47699aa99fd1f3ea452fd8ca09749666c17a333b
