### ISSUE TITLE
Make sample_type and name required fields on cell_line.json

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#29]

**Comment by malloryfreeberg** [comment]
This issue was fixed by @daniwelter .

However
- `cell_line.json` is now two separate schema (`immortalized_cell_line` and `primary_cell_line`).
- `sample_type` has been removed from sample subschemas, and is therefore no longer required.
- `name` has been moved up to `sample.json` and is therefore no longer required.
