### ISSUE TITLE
Add field to distinguish between left or right organ (e.g. kidney)

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#341]
**For which schema is a change/update being suggested?**

Specimen from organism. Specifically organ field (or related).

**What should the change/update be?**

Please describe the change you are requesting. Be as descriptive as possible. Possible requests can include, but aren't limited to:

This is unclear and should be discussed. We could:
* add new field with a CV for left or right
* enhance uberon or use a different ontology that will allow us to specify if the organ is the left or right one

It would be a shame if we were only able to record this in the sample description especially since the same dataset may have both sides.

**Why is the change requested?**

A contributor working with kidney pointed out that they record if the donated organ is the left or right kidney. They have done studies with both from the same organism and believe there are subtle differences. Biochemistry lab tests are run prior to donation to test left and right kidney before the decision is taken which to remove for donation.

We will likely need this for other organs where n=2.

**Comment by lauraclarke** [comment]
This feels like an expected but not current requirement. I am going to put it on ice for now

**Comment by malloryfreeberg** [comment]
Closing this ticket.

For some organs (e.g. lung), there are separate ontology terms for structures from the left lung or right lung. If there are instances where the ontology used to describe organs and organ parts is lacking information about "left" or "right", we should strive to improve the ontology instead of adding a left/right field explicitly to the schema.
