### ISSUE TITLE
ReadMe's for current spreadsheet directories

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/metadata-schema#364]
**For which schema is a change/update being suggested?**

/example/spreadsheets/current/template and filled

**What should the change/update be?**

Add readme files to both directories with descriptions of the current files. 

**What new field(s) need to be changed/added?**

File names with a description about each file.

**Why is the change requested?**

Eases a users ability to grab the correct template/example spreadsheet for there needs.

**Comment by lauraclarke** [comment]
Just to extend this, it would be good to have a naming convention for the files and for files names to change when they get updated.

e.g https://github.com/HumanCellAtlas/metadata-schema/blob/master/examples/spreadsheets/current/filled/Q4DemoSS2Metadata.xlsx has a name which suggests it was created in Q4 2017 but I know it has been updated since. This can create confusion.
