### ISSUE TITLE
Move protocols reference from project to sample json

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#38]

**Comment by lauraclarke** [comment]
Do we also have them in assay as there will be protocols there too

**Comment by daniwelter** [comment]
The exact future and nature of assay is still under discussion. The current representation of assay treats protocols very differently to the way they are represented in relation to sample. We are going to look at some actual data and how the submitters are going to give us the data in order to figure out how to best solve this

**Comment by lauraclarke** [comment]
Two important things to note

v4 will be used to collect pilot data and there will be assay protocols to collect. v4 must contain some method of collecting assay protocols.

If it is felt that assay protocols and sample protocols are sufficiently different that they need to be modelled differently (I would need to see strong evidence that that was actually true) then we need to think about what language we use to describe them because if the forms users have to fill out to collect the information are very different but they are both called protocols I worry it will be very confusing to users

I will send an email about this.

**Comment by daniwelter** [comment]
As per #36, in v5, protocols are referenced by the processes that implement them, and processes link to biomaterials, so there is no longer a need for a direct link from biomaterial to process.
