### ISSUE TITLE
Develop guidelines for metadata field naming

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/metadata-schema#419]
I have noticed there has been a great deal of disagreement over metadata field naming.  In trying to understand the source of these issues, I could not find any guidelines on the naming of class and fields.

The purpose of this ticket is to serve as a discussion point for creating such guidelines.  I believe docs/rationale.md could be a good location for such guidelines, as the rationale for naming is part of a design.

**Comment by malloryfreeberg** [comment]
Hi @diekhans . Thank you for bringing up this issue. I have started a draft [Metadata Schema Style and Formatting Guide](https://github.com/HumanCellAtlas/metadata-schema/blob/mf-metadata-style-guide/docs/schema_style_guide.md) and will be working on it over the next few weeks with other members of the metadata team to formalize our approach. Any feedback on the guide either now or in it's final form will be much appreciated!

Specifically, if you have any remaining questions/concerns not addressed in the guide, please let us know here so we can add them in.

**Comment by malloryfreeberg** [comment]
Copied from JIRA:

The metadata standard currently follows internal, undocumented style rules. These rules need to be documented so that future requesters of fields or outside (of the metadata/ingest team) developers are aware of the style rules and can maintain consistency.

**Acceptance criteria**

- Documentation in the metadata-schema repo giving guidance on what metadata schema field names should look like and what the expectations are to maintain consistency.
- Documentation merged into master

**Comment by lauraclarke** [comment]
- [ ]  Update Title/name guidance

The use of title has changes and so we now have title and name, I assume this needs to be updated

- [ ] Make the documentation around how $id works more specific

$id

It might be nice for an informational and context thing to explain the the $id is a resolveable url which points to the schema and we insert this at build time as it must contain the version of the schema which isn't defined within github

- [ ] Make the documentation around field name specificity clearer

Field names do not exist outside of the context of their containing structure. Fields in objects are not standalone, and the field names should not redundantly contain the structure name. NB This principle may change.

as you explained to me earlier with unqualified and qualified names it would be better to make this comment more explicit about that topic and but change the note to reflect the risk that is associated with that decision. Perhaps making a statement about the fact that field names must always be fully qualified in order to be unambiguous, this should go in the implementers' guide too

- [ ] Guideline field seems to contain a comment as well as text. This should be removed or updated to read as part of the guidance

guidelines: Instructions for how to fill in a valid value for the metadata field. This attribute is can be included on an as-needed basis when further clarification for how to fill in a metadata field would be helpful to data contributors. The guidelines value will appear in the metadata spreadsheet.

Example:

 "address": {
     "description": "Street address where the individual works.",
     "type": "string",
     "example": "0000 Main Street, Nowheretown, MA, 12091",
     "guidelines": "Include street name and number, city, country division, and postal code.",
     "user_friendly": "Street address"
 }
mf: We might merge the example and guidelines attributes into just the example attribute. We need to discuss use cases for separating them or keeping them together.

- [ ] Ontologies vs enum change

I would advocate changing this to Ontologies, Enum or free text. I think the sentiment is correct but doesn't state the caveat that enum's only work well where there is a short list.

For the example here

"The list of valid values is too diverse to be organized into a meaningful ontology or while awaiting the development of an appropriate ontology or ontology branch. If in doubt, check with one of the HCA ontologists!"

If there are more than 10 possible values, a free text field is probably still better as it means people don't need to consistently check if what they want is in the enum

**Comment by lauraclarke** [comment]
Extra bit

- [ ]  The structure doc should reference the style guide from a content perspective 

https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/structure.md

**Comment by hewgreen** [comment]
This is excellent. I barely have any comments.

1. I can't see where the style guide leans us towards generality where possible e.g. 'plate_based_sequencing' over smart seq. Or 'droplet seq' vs 10x.

2. It may be leaning away from style of individual schema docs but one thing we wrestled with when creating the imaging metadata was our general preferences for new schema. For example, do we have a preference to make more modules than types or visa versa? If I have group of fields that constitute an array e.g. contact info should these be a module or not? Given our remit of reusability what do we mean by that? Are we talking modules used in types or fields used elsewhere or are we talking about reusability in a more general interoperability sense? I think this sort of guidance will be needed when external groups write metadata.

**Comment by malloryfreeberg** [comment]
Tagging @zperova to address the "Extra bit" above as she's working on cleaning up those docs.

**Comment by malloryfreeberg** [comment]
> This is excellent. I barely have any comments.
>
> I can't see where the style guide leans us towards generality where possible e.g. 'plate_based_sequencing' over smart seq. Or 'droplet seq' vs 10x.
>
> It may be leaning away from style of individual schema docs but one thing we wrestled with when creating the imaging metadata was our general preferences for new schema. For example, do we have a preference to make more modules than types or visa versa? If I have group of fields that constitute an array e.g. contact info should these be a module or not? Given our remit of reusability what do we mean by that? Are we talking modules used in types or fields used elsewhere or are we talking about reusability in a more general interoperability sense? I think this sort of guidance will be needed when external groups write metadata.

I totally agree that we need to write down some guidelines for this. I think there are some generally guidelines the metadata team has been following, but there isn't anything written down. For example, a module should contain a set of fields that relate to each other in a meaningful way. 

I wrote the Style Guide under the assumption that one has already decided what needs to go in a schema, and now they want some direction on how to actually write up the JSON schema as per our guidelines. I think the discussion of how fields are organized across core, type, and module schemas would be best placed in the structure.md document in the metadata-schema repo.
