### ISSUE TITLE
Make title attribute user-friendly and Sentence case

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#501]
**For which schema is a change/update being suggested?**

I would like to request an update to all metadata schemas.

**What should the change/update be?**

I would like to change all schema `title` attributes from lowercase, snake_case terms to user-friendly Sentence case terms.

_NEW_ I would like to add to all schema a `name` attribute to be the programmatic name of the schema, which should always be the name of the schema file.

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

Currently the `title` attribute is not used anywhere. This attribute would be a good place to store a user-friendly schema name to be used as spreadsheet tab names, to append to custom field names (_e.g._ to generate "Organoid ID" from the `biomaterial_id` field in the `organoid` schema), and for displaying in things like the ingest UI and Data Portal. This change would be a patch change to all schemas.

_NEW_ Eventually ingest will need a programmatic way to access the name of the schema (currently parsing the URI which is **not** correct), so including this programmatic name in a `name` attribute would satisfy this requirement.

**Comment by malloryfreeberg** [comment]
@tburdett can you comment what the use case is for having a programmatic `title` and also a new `user_friendly_title`?

**Comment by tburdett** [comment]
Sure... this is not really a use case, rather it is a technical justification. @simonjupp may want to comment further, but I think I can summarise here.

The template generator utilises json dot syntax to create key IDs, mapping (crudely) JSON documents onto tabs in the sheet, and field names onto columns. So the form the template generator understands is `<schema_title.field_name>`. For example, `sequencing_protocol.local_machine_name`, resolves to tab `sequencing_protocol`, column `Local machine name`. 

The "friendly" column names are enabled because in the relevant sequencing_protocol [JSON schema](http://schema.integration.data.humancellatlas.org/type/protocol/sequencing/9.0.0/sequencing_protocol), the `local_machine_name` field has a `user_friendly` attribute which enables the column name to be presented nicely.

At the moment, the `title` attribute in the `sequencing_protocol` schema is ignored, because the schema name (`sequencing_protocol`) is populated from the file name (`sequencing_protocol.json`). However - **this is a bug** - we shouldn't be attaching this significance to the file name. We should really be using the `title` field instead. The change as proposed would leave no _correct_ way for the template generator to retrieve a key ID.

Having said all of that; I would be fine with modifying the `title` attribute to be the "user friendly" variant as long as we also introduced a new `name` field to use in the key ID at the same time.

**Comment by lauraclarke** [comment]
I think it makes sense for title to be the one which is computationally interpretable and user_friendly_title to be the human one as that matches our conventions elsewhere in the schema

**Comment by diekhans** [comment]
"title" implies user-friendly, so adding a "name" field, as Tony suggested, is very obvious in my mind.

**Comment by lauraclarke** [comment]
title is a JSON schema keyword which is means to contain the schema name looking at 

http://json-schema.org/latest/json-schema-core.html

If want to use name for the schema name we should use user_friendly_name for the user-friendly bit, consistent with our style and not using a JSON schema defined keyword for a purpose it isn't described for

**Comment by malloryfreeberg** [comment]
Ok, so the consensus is we need to have two attributes: one programmatic and one user-friendly. 

- `title`: programmatic name of the schema, should *always* be the name of the schema file (_e.g._ `"title": "organoid"` for the `organoid.json` schema)
- `user_friendly_title`: user-facing name of the schema to be used in the spreadsheet tabs, Data Browser, etc. (_e.g._ `"user_friendly_title": "Organoid"`

**Comment by diekhans** [comment]
the `title' keyword` is  defined here: https://json-schema.org/understanding-json-schema/reference/generic.html

Which appears to define both `title` and `description` as natural language strings.  Repurposing title as a programmatic `name` goes against the JSON schema specification.  While we are certainly free to do this, I think it will create confusion, both for people familiar with JSON schema and those who have an intuition about the work `title`.

**Comment by diekhans** [comment]
@malloryfreeberg I don't think there is consensus and that the json schema specification is being misinterpreted.

**Comment by lauraclarke** [comment]
@diekhans is that still true in draft 7? That book refers to draft 4.

**Comment by diekhans** [comment]
`title` and `description` are defined in the draft 7 validation specification as being strings for the user interface descriptions:

   https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#page-23

Using `name` as the programmatic, unqualified name would not conflict with the schema specification and is common usage when describing data structures.

**Comment by lauraclarke** [comment]
I was looking for examples from other peoples JSON schema definitions but struggling to find any. schema.org and bioschama.org seem to have their content well structured but I can't find actual JSON schema specifications. 

Is there a reason not to be specific in these field names such as schema_name and schema_user_friendly_name?

The problem with field names like title and name is they are non-specific and without documentation can be misinterpreted

**Comment by diekhans** [comment]
hi @lauraclarke 

The meta schema uses the title field:

   http://json-schema.org/draft-07/schema

The problem with trying to make globally description symbolic names is they just become cumbersome to use.  This detracts from code readability, as fields are programmatic names that are always used in context.

Many find `<schema>.schema_user_friendly_name` is harder to read than `<schema>.titile`, especially since title is a standard part of JSON schema and is common uses in both programming and English to be a natural language string (e.g. HTML `<TITLE>`).

These should be clearly documented and name clearly withing within context.  Programmers need to RTFM.

For use in other context outside of JSON, looking up a symbolic or natural language name for the context is approriate.  This prevents this strugle to find a single name that works well for all context and also allows secondary names to be changed without impact the schema.

**Comment by malloryfreeberg** [comment]
Proposal:

- `title`: user-facing name of the schema to be used in the spreadsheet tabs, Data Browser, etc. (_e.g._ `"title": "Organoid"`
- `name`: programmatic name of the schema, should always be the name of the schema file (_e.g._ "name": "organoid" for the `organoid.json` schema)

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Information about the cell suspension derived from the collected or cultured specimen",
    "additionalProperties": false,
    "title": "Cell suspension",
    "name": "cell_suspension",
    "type": "object",
    "properties": {}
}

```

**Comment by tburdett** [comment]
No complaints from me on this proposal. This satisfies both programmatic and user-facing requirements, and it doesn't break anything given that we're currently (albeit incorrectly) not using the `title` field programmatically, so this looks good

**Comment by diekhans** [comment]
thanks, @malloryfreeberg this is consistent with schema specification and what an object model design would tend to do. 

If other identifiers are needed for other uses, the schema would be a good place to centralize them.
