### ISSUE TITLE
Remove time_of_death from death.json

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/metadata-schema#741]
**For which schema is a change/update being suggested?**

I would like to request a change to the `death.json` schema.

**What should the change/update be?**

I would like to remove the field - `time_of_death` - from this schema because it can make donors identifiable.

**Why is the change requested?**

A previous discussion in ticket #335 said to remove process start/end_time because it can make a donor identifiable but in that same regard knowing time_of_death can make a donor identifiable. Ticket #742 is going to discuss adding process start/end_time in again with a guideline to not include if it makes a donor identifiable. Based on the outcome of that ticket I believe a discussion needs to be had about keeping or removing this field for similar reasoning.

**Comment by malloryfreeberg** [comment]
We actually have a use case for this (#539). One of the preview datasets was willing to give us month and year of death of the donor. In the end they didn't because the field is a JSON date-time format, which requires the full date and time to be considered valid against the schema. The contributors weren't comfortable putting dummy "00T00:00:00Z" at the end of their metadata, which is very reasonable. 

So, instead of deleting this field, I'd rather keep it, enable partial date-time submission to be valid to this field (and the other date-time fields mentioned in #539), and let contributors be able to control the level of identifiability based on what they can give us.

Also, the identifiability issue doesn't apply to mice :)

**Comment by malloryfreeberg** [comment]
I'm going to close this issue. There are currently no issues with keeping this field, and we have at least 1 use case to keep it. As mentioned, enabling the ability to supply a partial date-time is being tracked in #539.
