### ISSUE TITLE
Add process_start/end_time to process.json

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/metadata-schema#742]
**For which schema is a change/update being suggested?**

I would like to request an update to the `process.json` type schema.

**What should the change/update be?**

I would like to add the new fields - `process_start_time`, `process_end_time` - to this schema to allow data contributors to add when a process began/finished.

**What new field(s) need to be changed/added?**

1.
* Field name: process_start_time
* Field description: When the process started, in date-time format, yyyy-mm-ddThh:mm:ssZ.
* Required: no
* Example: 2019-01-16T12:00:00Z
* Guideline: Only include if providing the time doesn't make a donor re-identifiable.
2.
* Field name: process_end_time
* Field description: When the process finished, in date-time format, yyyy-mm-ddThh:mm:ssZ.
* Required: no
* Example: 2019-01-16T12:00:00Z
* Guideline: Only include if providing the time doesn't make a donor identifiable.

**Why is the change requested?**

A data contributor would like to include the start/end times for a process to help identify possible batch effects as their processes were completed months apart. A discussion needs to be had about whether or not to reintroduce these fields with the guideline to only include if they don't make a donor identifiable.

**Comment by daniwelter** [comment]
I would add to this that in the particular use case that brought about this discussion, only a start time is available, no end time, so it is not possible to calculate the length of the process.

**Comment by malloryfreeberg** [comment]
I think we can add a start and end time. I have the following suggestions for the field:

1. Remove "process_" from the beginning of each field to adhere to the Style Guide about fully qualified field names. e.g. `process.start_time` instead of `process.process_start_time`
1. The "in date-time format, yyyy-mm-ddThh:mm:ssZ" bit should go in the `guidelines` attribute instead of the `description`, as per the Style Guide.
1. "Only include if providing the time doesn't make a donor re-identifiable" seems out of place here. First, if the donor is a mouse, then identification isn't an issue. Second, different countries and institutes have different rules about what information is allowed to be released in terms of making an individual identifiable. There are lots of metadata fields that could contribute to this (age, ethnicity, disease, BMI, etc.), and we can't know which ones might possibly be identifiable. We rather should have this statement be a general guideline for any metadata shared with us, but ultimately it will depend on the source of the data. I recommend removing this from the guidelines.

**Comment by malloryfreeberg** [comment]
@willrockout if you're happy with the suggestions, feel free to make the changes.
