### ISSUE TITLE
Timcourse information required on cell suspension

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#755]
**For which schema is a change/update being suggested?**

`biomaterial_core.json`
or at least
`cell_suspension.json`

**What should the change/update be?**

add timecourse.json module

**Why is the change requested?**

Ingested dataset neuronal diff 125 day timecourse has timecourse information on cell suspension but this is not captured in a structured way. Conversion to MAGE tab requires detection of 'experimental factor' which for this experiment is timecourse. Ideally this would be captured in a structured way.

**Comment by malloryfreeberg** [comment]
If we now have a use case for this field being on both donor and cell suspension (and I suspect we'll get other biomaterials that need this in the future), and given our recent discussions on modularization (fields should be in a module if they are used in multiple places), I think we have enough reason to keep these fields in a module. 

However, we don't want to nest too deeply (cell suspension imports core imports timecourse), so I'm happy to add the timecourse field to cell_suspension.json (instead of biomaterial_core) which imports the timecourse module.

**Comment by hewgreen** [comment]
I like the sentiment not to nest too deeply. The alternative solution is to get rid of the module and add all of its fields to biomaterial core. This presumes the module won't be needed on a protocol or file. It depends how much we want to purge modules.

 I'm happy for either solution to fix the problem now and optimise this later on as required, maybe in light of even flatter schema.

**Comment by malloryfreeberg** [comment]
I'll go ahead and add the timecourse module to the cell suspension schema, to match what we have in the donor schema now.

If we demod later, we can unnest the timecourse fields in both schemas as the same time.
