### ISSUE TITLE
Ensure only code approved by appropriate reviewers gets merged into the DCP

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#866]
We will use a service/tool called "Pull Approve" to achieve this (https://www.pullapprove.com/).

Overview:
The DevSecOps team are going to sign up for a pullapprove account.
[PullApprove Overview](https://www.pullapprove.com/docs/)
[Enabling required status checks - GitHub](https://help.github.com/en/articles/enabling-required-status-checks)

**Comment by daniwelter** [comment]
Is this issue relevant for the metadata component? Metadata schemas already undergo a multi-person review process. None of the code in the metadata schema repo is actually deployed into the DCP, we only have a few scripts that we use locally to perform schema releases and check that the schemas confirm to our style guide.

**Comment by malloryfreeberg** [comment]
We probably need this so that we can prevent someone not on the core metadata updates team from merging in schema changes without going through the process. We are already almost there by restricting the members of the metadata-updates team to only those that commit to the repo. We can implement pull-approve with a rule that only someone on the metadata-update team can merge PRs.
