### ISSUE TITLE
Why does the library_construction field use enums?

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#92]
Why are the library_construction fields in rna.json and seq.json enums? I've had to add to these lists to ingest pilot data because "10x" wasn't an option. I'm also not entirely sure what the difference is between the fields - should they be the same? If so, do we need both? The descriptions are unclear to me:

rna.json: 
```
"description": "The general approach for sequencing library construction. e.g. Smart-seq, Drop-seq, 10x.",
"enum": [
                "unknown", 
                "CEL-seq", 
                "SMARTer Ultra Low RNA Kit", 
                "modified smart-seq2", 
                "smart-seq2", 
                "QUARTZ-Seq", 
                "10x_v2", 
                "drop-seq", 
                "inDrop", 
                "10x", 
                "10X"
], 
```

seq.json:
```
"description": "How the DNA sequencing library was prepared. e.g. Nextera XT, TrueSeq."
"enum": [
                "Nextera XT", 
                "TruSeq", 
                "modified Nextera XT", 
                "10X", 
                "10x"
], 
```

Unless there is a compelling reason to make these fields enums, would it be better to just make them strings to avoid restricting users? It's quite a pain to enforce matching to all these enums in light of things like capitalization, punctuations (drop-seq vs DropSeq), etc.

**Comment by dosumis** [comment]
Technique used should really be recorded using EFO.
On Dec 7, 2017 4:12 PM, "Mallory Freeberg" <notifications@github.com> wrote:

Why are the library_construction fields in rna.json and seq.json enums?
I've had to add to these lists to ingest pilot data because "10x" wasn't an
option. I'm also not entirely sure what the difference is between the
fields - should they be the same? If so, do we need both? The descriptions
are unclear to me:

rna.json:

"description": "The general approach for sequencing library
construction. e.g. Smart-seq, Drop-seq, 10x.",
"enum": [
                "unknown",
                "CEL-seq",
                "SMARTer Ultra Low RNA Kit",
                "modified smart-seq2",
                "smart-seq2",
                "QUARTZ-Seq",
                "10x_v2",
                "drop-seq",
                "inDrop",
                "10x",
                "10X"
],

seq.json:

"description": "How the DNA sequencing library was prepared. e.g.
Nextera XT, TrueSeq."
"enum": [
                "Nextera XT",
                "TruSeq",
                "modified Nextera XT",
                "10X",
                "10x"
],

Unless there is a compelling reason to make these fields enums, would it be
better to just make them strings to avoid restricting users? It's quite a
pain to enforce matching to all these enums in light of things like
capitalization, punctuations (drop-seq vs DropSeq), etc.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/HumanCellAtlas/metadata-schema/issues/92>, or mute the
thread

**Comment by malloryfreeberg** [comment]
I think recording the EFO ontology term is a separate (but still important) issue from recording information about what library construction protocol was followed. 

E.g. there is the EFO term "nucleic acid library construction protocol" (EFO_0004184) but I think the `library_construction` fields were meant to be more specific than that term.

**Comment by malloryfreeberg** [comment]
This will eventually be an EFO term and is related to #128
