### ISSUE TITLE
Add new field file_core.encoding.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#971]
**For which schema is a change/update being suggested?**

I would like to request an update to the `file_core.json` schema.

**What should the change/update be?**

I would like to add a new field - `encoding` - to this schema to indicate the encoding of the file.

**What new field(s) need to be changed/added?**

*e.g.*:
* Field name: encoding
* Field description: The encoding of the file.
* Field type: string
* Required: no
* Examples: gzip
* CV or enum: yes, use existing MIME content-encoding values

**Why is the change requested?**

Data consumers need to be able to tell what the format and encoding of the files are that they get from the DS so the files can be processed accordingly.

See conversations in https://github.com/HumanCellAtlas/data-browser/issues/470 for more about this topic.

**Comment by ESapenaVentura** [comment]
I'll take it!

**Comment by ESapenaVentura** [comment]
I've been thinking about this, and after reading a little bit about mime types, I want to suggest that, instead of an enum, we make this a pattern.

Currently, for what I understood about in the DCP media types documents, the CLI actually reads and differentiates between metadata (json) and data. The kind of data that we are getting are:

- fastq
- fastq.gz
- pdf (For protocols)
- Images

But we can't discard that we will be receiving other kind of files in the future (Or variants of the files, such as gzipped images, pdf, or even zipped ones). For that matter, I believe that making the encoding that we are able to capture a pattern is a better approach, as we will be able to capture more elements in the future. This is the pattern that I've been working on:

"(image|application|text)/[a-z0-9\.]+(\+[g]*zip){0,1}"

This should be able to capture things as "text/fastq" (Or plain; I think plain would be a better approach, as it's actually a plain text file, but I want opinions on this), "text/plain+gzip", "image/png", "image/tiff", "application/octet-stream", etc, making it pretty flexible for our purposes.

The only problem I see is that I don't know if we should expect the user to input the correct encoding under MIME standards, or if we should give them a list of options and programmatically capture and write the actual type. @HumanCellAtlas/wranglers @simonjupp @daniwelter, any ideas?

**Comment by rexwangcc** [comment]
Cross-posting some relevant issues from Slack: 

^I want to quickly follow up on the above Mice bundles discussion and update everyone that are involved(@Marcus Kinsella@ambrose):

We (secondary-analysis) tried to run a few Optimus workflows on the mice bundles @malloryfreeberg  helped ingested in integration. They all failed due to an error in the Adapter workflow: we have been using `f for f in primary_bundle.files.values() if f.file_format == 'fastq.gz'` to extract the sequence_file information from the bundles, but for these mice bundles, they have `sequence_file.file_core.format` equals to `fastq`, even though the actual files are in `.gz` format.

We have 2 questions here:
1. For this run, should we update our code to match both fastq.gz and fastq? (e.g. `f.file_format in ('fastq', 'fastq.gz')`)
2. If this field in the spreadsheet is filled by human hands, how can we prevent future mismatches? (imagine someone in the future puts something like `FastqGz` there). Should we use some sort of ontology id here for fastq?

**Comment by ESapenaVentura** [comment]
Continuing with the cross-posting updates from slack and some personal thoughts:

In order to be able to differentiate between file types, we shouldn't be trusting the metadata. Let's not forget that this is introduced manually, right now by the wrangler team but, in the future, this will be entirely contributor-based. Even though Fastq is a pretty common file format, we cannot expect that it will always be written the same way.

With this in mind, we propose that there is some kind of programmatic way to detect the file type, that actually checks on the files. There are several tools fitted for this job: 

- ATM, the DCP cli uses a library (libmagic) that tries to "sniff" the data type (DCP media types document, page 4).

- The "file" command, given a "magic file list" with patterns to detect different type of data, can look through files looking for patterns and output its format. A good example that contains a magic file list to detect several bioinformatic files can be found in [this repo](https://github.com/lindenb/magic).

I am sure that there are way many more tools, but these are the two we found most interesting. I think there is an interesting option in combining both of them, as the cli (Correct me if I'm wrong, @sampierson) should have appended the file's media type (e.g., text/plain, text/plain+gz if it's gzipped, application/octet-stream if it's a binary file with no standard in mime, such as a bam). From this, we could extract if the file is gzipped, and check with the "file" command its underlying format. Using this combination of libraries has the advantage that is pretty flexible for the future (e.g., if we decide to accept bam files, we just need to add the bam to the magic file list to be able to detect it)

@malloryfreeberg Has proposed that we do some semantic validation of the metadata after upload, with the scope of populating the file.format field with the correct extension. By doing so, we could define an enum for the format, which could greatly help both the pipelines team and the data portal, as they would be able to check on specific values. An enum of this kind could have the form of: 
["fastq", "fastq+gz", "pdf", "other"]

And we could add more formats as we expand the formats of data that we are accepting/processing.

**Comment by ESapenaVentura** [comment]
We decided that we would not add a user-filled field about the encoding.
