### ISSUE TITLE
Change `donor_organism.genus_species` to be required

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-schema#999]
Sorry don't have time to fill out the template. 

https://schema.dev.data.humancellatlas.org/type/biomaterial/15.3.0/donor_organism

does not list `genus_species` as required but it does `sex`. This does not compute to the amateur biologist in me. Why would the lab know the sex (gender) of a donor but not its species?

**Comment by rexwangcc** [comment]
FYI, link to the Slack discussion: https://humancellatlas.slack.com/archives/C49TW3RV5/p1559079693046200

**Comment by malloryfreeberg** [comment]
The reason `genus_species` is not required is because `ncbi_taxon_id` is. These two values represent  the same thing. An NCBI taxon ID only ever points to 1 genus species name, and a genus species name is only ever associated with 1 taxon ID. e.g. "homo sapiens" is always 9606 and "mus musculus" is always 10090. We decided to make the `ncbi_taxon_id` field required instead of `genus_species` because the value is an integer and has less of a chance of being formatted or entered incorrectly, whereas the `genus_species` field could be filled with things like "human", "Human", "homo sapiens", "Homo sapiens", "homo sapien" (misspelling), etc, making it more difficult for programmatic usage of the field. 

We have ontologized `genus_species` now so that one could be sure the `genus_species.ontology` and `genus_species.ontology_label` fields are standardized (although they are still manually filled in by a wrangler, so room for human error), but that feature was implemented after making `ncbi_taxon_id` required.

We would love, in the future, to have automatic curation of the `genus_species` field where a user supplies just the `ncbi_taxon_id` value and the `genus_species` fields are filled in for them automatically using a lookup. 

In principle, I don't have a problem with also making the `genus_species` field required. This would be a major schema version change and I'm aware we are in a major version change "freeze" at the moment.

**Comment by hannes-ucsc** [comment]
Makes sense. All bundles in the HCA currently have `genus_species` so making it required shouldn't break anything.

`ncbi_taxon_id` is on biomaterial core. What about biomaterials other than `donor_organism`? Is there a 1:1 mapping between `ncbi_taxon_id` and ontologized fields in those? If so we could we derive `ncbi_taxon_id` at ingest time and effectively prohibit it from being supplied by wranglers.

**Comment by malloryfreeberg** [comment]
> What about biomaterials other than donor_organism? Is there a 1:1 mapping between ncbi_taxon_id and ontologized fields in those?

Yes, the `ncbi_taxon_id`:`genus_species` mapping is the same regardless of the type of biomaterial.

> we could derive ncbi_taxon_id at ingest time and effectively prohibit it from being supplied by wranglers

Absolutely! We have plans to do some of this automatic curation in the future (not sure exactly where it is on the roadmap). Ideally, contributors/wranglers only supply one of taxon ID or genus species, and we automatically map the other fields/ontologies.

Can anyone else on the @HumanCellAtlas/metadata-updates team think of a reason to not make `genus_species` required?

**Comment by daniwelter** [comment]
Can I request that if genus_species is made required for donor_organism, it be made required for all biomaterials? The field is technically a core field and only lives at type level because it imports an ontology module and we have a policy that no references should be imported at the core level.

**Comment by hannes-ucsc** [comment]
We need to do something about this. There is now metadata in the wild that exploits the ambiguity:

https://github.com/DataBiosphere/azul/issues/3041

There is no point in allowing metadata producers to supply two independent properties of low cardinality whose values are dependent on each other in a bijection. The correct data model is to only allow one and to derive the other, or some variant of that, like enforcing that both are present and consistent. But making one optional and the other one required without any validation to ensure they are consistent is sheer madness.

**Comment by clairerye** [comment]
Agreed. Looking at the comments above it looks like it was all agreed this was a sensible change to make and was just waiting on being able to evolve the schema, which we can now do. The next changes are already in progress but I will chat with the team to see if we can get this in next, I also see you have a ticket to collect other fields that azul requires so it might be good to combine this with others if there are other fields that are also required.

**Comment by hannes-ucsc** [comment]
We will inventory for other fields that are de-facto required and get back to you:

https://github.com/DataBiosphere/azul/issues/3072

**Comment by NoopDog** [comment]
Hi @ESapenaVentura, it seems that `ncbi_taxon_id` and `genus_species` are conveying the same information. Can one of them be deleted?

 Also, it looks like `ncbi_taxon_id`, although it uses an ontology, is not "ontologized" (it does not use an ontology module). Perhaps a way forward here is to:

1.  Remove `ncbi_taxon_id` from the `biomaterial_core`.
1.  Move `genus_species` from each of the biomaterial types to `biomaterial_core` and make it required.

This would then:

1. Remove the redundancy.
1. Make `genus_species` required.
1. Use an ontologized field with specified restrictions to represent species information. 

A more gentle way forward could be to:

1.  Deprecate `ncbi_taxon_id` on `biomaterial_core`.  (Do we have a deprecation mechanism?)
1.  Move `genus_species` from each of the biomaterial types to `biomaterial_core` and make it required.
1.  Delete `ncbi_taxon_id` on `biomaterial_core`at some point in the future.

Interested in your thoughts on these approaches.

Cheers,
Dave

**Comment by hannes-ucsc** [comment]
@NoopDog, multiple people have expressed an opinion on this. Your comment makes it sound as if this conversation is just between you and @ESapenaVentura. I think you should learn to communicate in a more inclusive manner.
